# Generated by Django 5.2.8 on 2025-11-27 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kapasitas', models.IntegerField()),
                ('fasilitas', models.TextField(blank=True)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Verifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=10)),
                ('catatan_admin', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.ruangan')),
            ],
        ),
    ]
