# Generated by Django 5.2.8 on 2025-11-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='no_hp_penanggung',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. HP Penanggung Jawab'),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='penanggung_jawab',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Penanggung Jawab Kegiatan'),
        ),
    ]
