# Generated by Django 5.2.8 on 2025-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_peminjaman_no_hp_penanggung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='hari',
            field=models.CharField(blank=True, choices=[('SENIN', 'Senin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KAMIS', 'Kamis'), ('JUMAT', 'Jumat'), ('SABTU', 'Sabtu'), ('MINGGU', 'Minggu')], max_length=10),
        ),
    ]
