# Generated by Django 5.2.8 on 2025-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_peminjaman_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='alasan_pembatalan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Pembatalan oleh Pemohon'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu Verifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan oleh Pemohon')], default='MENUNGGU', max_length=20),
        ),
    ]
