# Generated by Django 5.2.8 on 2025-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0004_peminjaman_alasan_pembatalan_alter_peminjaman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='minta_batal',
            field=models.BooleanField(default=False, verbose_name='User mengajukan pembatalan?'),
        ),
    ]
