# Generated by Django 5.2.8 on 2025-12-03 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0005_peminjaman_minta_batal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='pembatalan_disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembatalan_disetujui_oleh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='pembatalan_disetujui_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu Verifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('MENUNGGU_PEMBATALAN', 'Menunggu Pembatalan'), ('DIBATALKAN', 'Dibatalkan oleh Pemohon'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20),
        ),
    ]
